elementor/hello-plus

includes/utils.php
modules/template-parts/documents/document-base.php

Ensure elements are not rendered twice in the editor or in preview mode

Add checks to avoid double rendering of elements [TMZ-181] [TMZ-195]

---

modules/forms/classes/form-base.php
modules/forms/classes/render/widget-form-render.php
modules/forms/fields/acceptance.php
modules/template-parts/classes/render/widget-footer-render.php
modules/template-parts/classes/render/widget-header-render.php
modules/template-parts/documents/document-base.php
modules/template-parts/templates/header.php

- Ensure that all output is escaped late

Refactor code to escape all output late [TMZ-223]

---

modules/admin/assets/js/components/preview/preview-with-image.js

- refactor approach for previews

Mimic the standard kits look [TMZ-335]

---

modules/content/assets/scss/hello-plus-contact.scss
modules/content/widgets/contact.php

Fix box padding for stretched map, hide map controls in quick info preset [TMZ-452]

---

modules/template-parts/documents/ehp-document-base.php

- Prevent displaying of location elements from pro when editing Hello+ Docs

[TMZ-661] Fix issue with preview oh Hello+

---

modules/admin/assets/js/components/onboarding/screens/get-started.js
modules/admin/assets/js/components/onboarding/screens/install-kit.js
modules/admin/assets/js/components/onboarding/screens/ready-to-go.js
modules/admin/assets/js/pages/onboarding-page.js
modules/admin/assets/js/providers/admin-provider.js
modules/admin/classes/rest/onboarding-settings.php

- This allows filtering of the label by the theme

Tweak: Move onboarding wizard labels to BE [TMZ-499]

---

modules/template-parts/assets/js/handlers/hello-plus-header-fe.js

Purpose: Added optimization for HelloPlusHeader scroll handling using requestAnimationFrame to prevent excessive DOM updates.
Main changes:
- Added scrollTimeout property to track and cancel redundant animation frames
- Implemented cancelAnimationFrame to prevent multiple simultaneous scroll handlers
- Created new onScrollEnd method to update floating bars height after scrolling completes

Header + Floating Bars: fix wobbly header when floating bars is not sticky [TMZ-706]

---

includes/utils.php
modules/template-parts/assets/js/handlers/hello-plus-header-fe.js
modules/template-parts/assets/scss/hello-plus-header.scss
modules/template-parts/classes/render/widget-header-render.php
modules/template-parts/widgets/ehp-header.php

Purpose: Adds WooCommerce cart functionality to the Hello Plus Header component with dropdown menu and accessibility controls.
Main changes:
- Adds cart icon button and dropdown menu with items, subtotal, and checkout links
- Implements inert attribute for accessibility and keyboard navigation using new menuCart handlers
- Adds document-level click/escape key handlers to close cart when clicking outside or pressing ESC

Header: Menu cart [TMZ-558]

---

includes/utils.php
modules/admin/classes/rest/onboarding-settings.php
modules/template-parts/components/checklist.php

Purpose: Add backward compatibility to is_licence_has_feature method and update kit filtering to work with new taxonomies structure in Elementor API response.
Main changes:
- Created is_licence_has_feature_compatible helper method using ReflectionMethod to handle different parameter counts
- Updated filter_kits_by_theme to use 'taxonomies' instead of 'categories' in API response structure
- Added existence check for ElementorPro\Modules\Checklist\Steps\Setup_Header class before adding filter

Fix: Refactor theme filter and add compatibility layer [TMZ-710]

---

hello-plus.php
modules/template-parts/assets/js/handlers/hello-plus-header-fe.js
modules/template-parts/assets/scss/hello-plus-header.scss
modules/template-parts/classes/render/widget-header-render.php
modules/template-parts/widgets/ehp-header.php
package-lock.json
readme.txt

Purpose: Adds menu cart functionality to Hello Plus plugin, integrating WooCommerce shopping cart into the header component.
Main changes:
- Implement toggle mechanism for cart popup with keyboard/click handlers and accessibility features
- Add menu cart UI components with product display, subtotal, and checkout buttons
- Update header styling with cart-specific CSS variables and responsive design

Release: Release version 1.7.0

---

modules/template-parts/widgets/ehp-header.php

Purpose: Add filtering capability to upsale data in Ehp_Header widget to enable customization of promotion content.
Main changes:
- Implemented 'helloplus_header_upsale_data' filter hook to allow modification of upsale data array

Tweak: Allow filtering upsale data [TMZ-759]

---

modules/admin/classes/rest/onboarding-settings.php
package-lock.json
package.json
readme.txt

Purpose: Fix kit filtering to consistently return an array in WordPress admin onboarding settings by using array_values.
Main changes:
- Applied array_values() to ensure kits are returned as sequentially indexed array
- Modified filter_kits_by_theme function to maintain consistent return format
- Updated package version from 1.7.0 to 1.7.1

Internal: Tweak kit filtering to always return an array [TMZ-789]

---

.github/workflows/cherry-pick-pr.yml

Purpose: Add empty cherry-pick detection and handling to the GitHub cherry-pick workflow to prevent failed operations when changes already exist.
Main changes:
- Implemented detection logic for empty cherry-picks using exit code and git status checks
- Added creation of informational PRs for skipped cherry-picks that are automatically closed
- Preserved existing conflict resolution handling with improved error reporting

Internal: Handle empty cherry pick scenario [TMZ-769]

---

modules/template-parts/widgets/ehp-header.php

Purpose: Fix conditional display of contact buttons style controls in the header widget for the "connect" layout preset.
Main changes:
- Replaced simple condition with complex OR/AND conditions to handle both regular and "connect" layout presets
- Updated style section label from "Call to Action" to more specific "CTA Button"

Fix: Show contact buttons style controls for connect [TMZ-714] [TMZ-807]

---

modules/template-parts/classes/runners/import.php

Purpose: Add functionality to automatically activate imported headers and footers by unpublishing existing ones before import.
Main changes:
- Added unpublish_by_doc_type method to set existing header/footer documents to draft status
- Implemented document type checking to target only header and footer template types
- Integrated unpublishing step within the template import process workflow

Tweak: Activate header and footer on import [TMZ-795]

---

modules/forms/module.php

Purpose: Remove elementor-common dependency from forms frontend script to ensure functionality for logged out users.
Main changes:
- Removed 'elementor-common' from frontend script dependencies while preserving required dependencies

Fix: Refactor script dependencies to work when user is logged out [TMZ-797]

---

modules/template-parts/assets/scss/hello-plus-header.scss

Purpose: Update responsive menu CSS to selectively hide buttons while preserving container structure for better mobile UX.
Main changes:
- Replaced blanket hiding of CTA container with selective hiding of buttons and responsive dropdowns
- Maintained visibility of parent container to support other potentially needed elements

Tweak: Ensure responsive menu works as expected [TMZ-810]

---

modules/template-parts/classes/render/widget-header-render.php
modules/template-parts/module.php
modules/template-parts/widgets/ehp-header.php

Purpose: Fix header widget visibility and navigation issues by improving button toggle logic and correcting component ordering.
Main changes:
- Enhanced should_show_button_toggle() logic to check for empty menus and available buttons
- Fixed import path for menu cart component with proper namespace structure
- Moved CTA section to proper position in the content tab rendering sequence

Fix: position of tab, visbility of hamburger menu, add to cart [TMZ-829] [TMZ-833] [TMZ-834]

---

modules/template-parts/assets/js/handlers/hello-plus-header-fe.js

Purpose: Add window resize handler to recalculate header height for proper floating bar positioning.
Main changes:
- Added handleOffsetTop() call in onResize() event handler to adjust header dimensions during window resizing

Tweak: Recalculate height when resizing [TMZ-830]

---

.github/actions/build-plugin/action.yml
.github/actions/deploy-to-wordpress-org/action.yml
.github/actions/install-svn/action.yml
.github/actions/prepare-plugin-env/action.yml
.github/actions/validate-plugin-build/action.yml
.github/workflows/one-click-release.yml

Purpose: Refactor GitHub Actions workflow to use modular composite actions for WordPress plugin deployment pipeline.
Main changes:
- Created 5 reusable composite action components with defined inputs/outputs for build, validation, and deployment
- Extracted environment preparation logic into dedicated prepare-plugin-env action
- Reorganized one-click-release workflow to use modular actions instead of inline shell commands

Internal: Implement modular action approach [TMZ-804]

---

hello-plus.php
modules/template-parts/module.php
package-lock.json
package.json
readme.txt

Purpose: Fix AJAX Add to Cart button getting stuck in loading state by adding missing header validation in cart fragments.
Main changes:
- Added validation check for theme support and empty header in add_to_cart_fragments method
- Updated plugin version from 1.7.4 to 1.7.5 across configuration files

Fix: AJAX Add to Cart button gets stuck [TMZ-863]
